directory: ~/Music_beets
library: ~/Music_beets/library.db
import:
  copy: yes
  move: no
  write: no
plugins: fetchart web 
paths:
  default: $albumartist/$album%aunique{}/$track-$title
  singleton: Non-Album/$artist/$title
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '\s+': '_'
